# Generated by Django 4.2 on 2023-04-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='core_user',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='core_user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
