# Generated by Django 4.2 on 2023-04-26 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_core_user_bio_core_user_dob_core_user_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='core_user',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
