# Generated by Django 4.2 on 2023-04-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_core_user_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core_user',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='core_user',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
