# Generated by Django 4.2.1 on 2023-05-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_alter_brewery_address_1_alter_brewery_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core_user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='core_user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
